name: pagina
on: workflow_dispatch
jobs:
  web-despl:
    runs-on: ubuntu-latest
    steps:
      - name: Desplegando pagina web
        run: echo "Desplegando pagina web"
      - name: Print bye
        run: echo "web"
